// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qixoidricuounrfucmwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeG9pZHJpY3VvdW5yZnVjbXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNDE4ODMsImV4cCI6MjA1NjcxNzg4M30.Lju_cvxjkjOZguO_yowu3Y-gcH4e3Bw8Tey0P9zOPCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);